services:
  mysql:
    build: ./docker/mysql
    image: deploy-mysql:latest
    container_name: mysqldeploy
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal # 내부 네트워크 연결
    expose:
      - "3306" # 외부에서 접근 불가능, 내부 네트워크에서만 사용 가능

  rabbitmq:
    build: ./docker/rabbitmq
    image: deploy-rabbitmq:latest
    container_name: rabbitmqdeploy
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - internal
    expose:
      - "5672"
      - "15672"

  redis:
    build: ./docker/redis
    image: deploy-redis:latest
    container_name: redisdeploy
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - internal
    expose:
      - "6379"

  backend:
    build:
      context: ./backend/ttabong
      dockerfile: Dockerfile
    image: depoloy-backend:latest
    container_name: backenddeploy
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: always
    depends_on:
      - mysql
      - redis
      - rabbitmq
    networks:
      - internal
    ports:
      - "8080:8080" # 외부에 직접 공개되지 않고 내부 네트워크에서만 접근 가능

  #frontend:
  #  build:
  #    context: ./frontend/ttabong
  #    dockerfile: Dockerfile
  #  image: frontend_builder
  #  container_name: frontend_deploy
  #  networks:
  #    - internal
  #  expose:
  #    - "3000" # 외부 접근 차단, 내부에서만 접근 가능

  nginx:
    build:
      context: ./frontend/ttabong
      dockerfile: Dockerfile
    image: deploy-nginx:latest
    container_name: nginxdeploy
    volumes:
      - ./docker/nginx/local_nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
      #  - frontend
      - backend
    ports:
      - "80:80" # 외부에서 HTTP 접근 허용
      - "443:443" # 외부에서 HTTPS 접근 허용 (필요 시)
    networks:
      - internal # 내부 네트워크 연결 (Backend, Frontend 연결)
      - external

networks:
  internal:
    driver: bridge
    internal: true # 🔥 내부 네트워크이므로 외부 접근 차단
  external:
    driver: bridge # 🔥 외부에서 접근 가능 (nginx만 연결)

volumes:
  mysql_data:
  rabbitmq_data:
  redis_data:
