concurrent = 1
check_interval = 0

[[runners]]
  name = "recreate-runner"
  url = "https://lab.ssafy.com"
  token = "glrt-t3_-QsqzG3UchQbdG_nZUsY"
  executor = "docker"
  limit = 2
  environment = ["DOCKER_HOST=tcp://docker-dind:2375"]
    [runners.docker]
    image = "alpine:latest"
    privileged = true
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]
